### ISSUE TITLE
AvgDistance is wrong

### ISSUE THREAD

**Issue by CreamNuts** [francescotonini/object-aware-gaze-target-detection#11]
https://github.com/francescotonini/object-aware-gaze-target-detection/blob/ca9522c92b68f14c66af712db23a06896c6d6fff/src/criteria/evals/GazePointAvgDistance.py#L72-L77

Average distance is average of all distances between prediction and targets. 
But that code calculate distance between prediction and average of targets. 

Generally, prior is smaller than latter.

**Comment by francescotonini** [comment]
Hi, thanks for pointing that out. To clarify, we calculate the average distance as in prior literature on gaze and following the definition from the GazeFollow paper ("Where are they looking?", NeurIPS 2015), which is "[...] the Euclidean distance between our prediction and the average of ground truth annotations."
