### ISSUE TITLE
An error occurred while reading videoattentiontarget dataset

### ISSUE THREAD

**Issue by chenwenhe11** [francescotonini/object-aware-gaze-target-detection#6]
Hello, when I run the following code when processing data, I get an error.
Run the code as follows:
python scripts/videoattentiontarget_get_aux_faces.py --dataset_path /path/to/videoattentiontarget --subset train
The error is reported as follows:
target_get_aux_faces.py", line 24, in
df = pd.read_csv(
pandas.errors.ParserError: Too many columns specified: expected 7 and found 2

Have you encountered this problem and how did you solve it?

**Comment by Y445n9** [comment]
Author may forget to provide train.csv or test.csv in videoattentiontarget dataset, as it dosen't exist in [videoattentiontarget](https://www.dropbox.com/s/8ep3y1hd74wdjy5/videoattentiontarget.zip?dl=0). Can author provide it?

**Comment by francescotonini** [comment]
Dear @chenwenhe11 and @Y445n9, I added both files to the repo and updated the pre-processing instructions. Please re-open this issue should you have further problems with the matter. Thanks.
